package greekquizgen.gui;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import greekquizgen.Generator;

/**
*
* @author abraao
*/
public class Gui extends javax.swing.JFrame {

   /**
    * Creates new form Gui
    */
   public Gui() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jPanel1 = new javax.swing.JPanel();
       jLabel1 = new javax.swing.JLabel();
       txtPalavra = new javax.swing.JTextField();
       jLabel2 = new javax.swing.JLabel();
       jScrollPane1 = new javax.swing.JScrollPane();
       txtExplicacao = new javax.swing.JTextArea();
       jLabel3 = new javax.swing.JLabel();
       btnNovo = new javax.swing.JButton();
       btnAnterior = new javax.swing.JButton();
       btnProximo = new javax.swing.JButton();
       jScrollPane2 = new javax.swing.JScrollPane();
       txtResposta = new javax.swing.JTextArea();
       btnGerar = new javax.swing.JButton();
       btnCarregar = new javax.swing.JButton();
       jLabel4 = new javax.swing.JLabel();
       txtArquivo = new javax.swing.JTextField();
       btnInicio = new javax.swing.JButton();
       btnFim = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

       jLabel1.setText("Palavra");

       jLabel2.setText("Explicação");

       txtExplicacao.setColumns(20);
       txtExplicacao.setRows(5);
       jScrollPane1.setViewportView(txtExplicacao);

       jLabel3.setText("Resposta");

       btnNovo.setText("Novo");
       btnNovo.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               btnNovoActionPerformed(evt);
           }
       });

       btnAnterior.setText("Anterior");
       btnAnterior.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               btnAnteriorActionPerformed(evt);
           }
       });

       btnProximo.setText("Proximo");
       btnProximo.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               btnProximoActionPerformed(evt);
           }
       });

       txtResposta.setColumns(20);
       txtResposta.setRows(5);
       jScrollPane2.setViewportView(txtResposta);

       btnGerar.setText("Gerar");
       btnGerar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               btnGerarActionPerformed(evt);
           }
       });

       btnCarregar.setText("Carregar");
       btnCarregar.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               btnCarregarActionPerformed(evt);
           }
       });

       jLabel4.setText("Arquivo:");

       btnInicio.setText("Inicio");
       btnInicio.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               btnInicioActionPerformed(evt);
           }
       });

       btnFim.setText("Fim");
       btnFim.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               btnFimActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(txtPalavra)
                   .addComponent(jScrollPane1)
                   .addComponent(jScrollPane2)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jLabel4)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(txtArquivo))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel1)
                           .addComponent(jLabel2)
                           .addComponent(jLabel3))
                       .addGap(0, 0, Short.MAX_VALUE))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(btnCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                       .addComponent(btnInicio)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(btnAnterior)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(btnProximo)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(btnFim)))
               .addContainerGap())
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(txtPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jLabel2)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jLabel3)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel4)
                   .addComponent(txtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(18, 18, 18)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(btnNovo)
                   .addComponent(btnAnterior)
                   .addComponent(btnProximo)
                   .addComponent(btnGerar)
                   .addComponent(btnCarregar)
                   .addComponent(btnInicio)
                   .addComponent(btnFim))
               .addContainerGap())
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addContainerGap())
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addContainerGap())
       );

       pack();
   }// </editor-fold>                        

   private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {                                  

	   if(question.word == null) {
		   questions.add(question);		   
	   } 

	   question.word = txtPalavra.getText();
	   question.explanation = txtExplicacao.getText();
	   question.answer = txtResposta.getText();
	   
	   indice = questions.size()-1;
	   question = new Question();
	   txtPalavra.setText("");
	   
	   Gui.this.setTitle("Indice:" + indice);
   }                                       

   private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {
	   
	   File fp = new File(txtArquivo.getText() + ".txt");
		
		if(fp.exists()) {
			fp.delete();
		}
		
		StringBuffer archive = new StringBuffer();
		
		for(Question q: questions) {
			archive.append(q.word).append("@").append(q.explanation).append("@").append(q.answer).append("\n");
		}
		
		BufferedWriter bf;
		try {
			bf = new BufferedWriter(new FileWriter(fp));
			bf.write(archive.toString());
			
			bf.flush();
			bf.close();	   
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

	 //Custom button text
	   Object[] options = {"Vocabulary",
	                       "Grammar",
	                       "Cancel"};
	   int n = JOptionPane.showOptionDialog(Gui.this,
	       "What type are you generating?",
	       "Type",
	       JOptionPane.YES_NO_CANCEL_OPTION,
	       JOptionPane.QUESTION_MESSAGE,
	       null,
	       options,
	       options[2]);
	   
	   if(n < 2) {
		   try {
			Generator.gerar(questions, txtArquivo.getText() + ".dat", n);
		} catch (IOException e) {
			e.printStackTrace();
		}
	   }
   }                                        

   private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {                                            
	   
	   question.word = txtPalavra.getText();
	   question.explanation = txtExplicacao.getText();
	   question.answer = txtResposta.getText();
	   
	   indice--;
	   if(indice < 0) {
		   indice = 0;
	   }
	   
	   question = questions.get(indice);
	   
	   txtPalavra.setText(question.word);
	   txtExplicacao.setText(question.explanation);
	   txtResposta.setText(question.answer);
	   
	   Gui.this.setTitle("Indice:" + indice);
   }                                           

   private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {                                           
	   
	   question.word = txtPalavra.getText();
	   question.explanation = txtExplicacao.getText();
	   question.answer = txtResposta.getText();
	   
	   indice++;
	   if(indice >= questions.size()) {
		   if(questions.size()==0) {
			   indice = 0;
		   } else {
			   indice = questions.size()-1;
		   }
	   }
	   
	   question = questions.get(indice);
	   
	   txtPalavra.setText(question.word);
	   txtExplicacao.setText(question.explanation);
	   txtResposta.setText(question.answer);
	   
	   Gui.this.setTitle("Indice:" + indice);
   }                                          

   private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) { 
	   
	   questions = new ArrayList<Question>();
	   indice = 0;
	   
	   Gui.this.setTitle("Question: " + indice);
	   
       try {
//			List<String[]> words = new ArrayList<String[]>();
			FileReader fr = new FileReader(txtArquivo.getText() + ".txt");
			BufferedReader rd = new BufferedReader(fr);
			
			String line = rd.readLine();
			
			while(line != null) {
				String lineSplit[] = line.split("@");
				
				Question quest = new Question();
				quest.word = lineSplit[0];
				quest.explanation = lineSplit[1];
				quest.answer = lineSplit[2];
				
				questions.add(quest);
				
				line = rd.readLine();
			}
			rd.close();
       } catch(Exception e) {
    	   e.printStackTrace();
       }
       
	   indice = 0;
	   question = questions.get(indice);
	   
       if(question.word != null) {
    	   txtPalavra.setText(question.word);
    	   txtExplicacao.setText(question.explanation);
    	   txtResposta.setText(question.answer);
       }
   }                                           

   private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {                                          
	   indice = 0;
	   
	   question = questions.get(indice);
	   
	   txtPalavra.setText(question.word);
	   txtExplicacao.setText(question.explanation);
	   txtResposta.setText(question.answer);
	   
	   Gui.this.setTitle("Indice:" + indice);
   }                                         

   private void btnFimActionPerformed(java.awt.event.ActionEvent evt) {                                       
	   indice = questions.size()-1;
	   
	   if(indice<0)indice=0;
	   
	   question = questions.get(indice);
	   
	   txtPalavra.setText(question.word);
	   txtExplicacao.setText(question.explanation);
	   txtResposta.setText(question.answer);
	   
	   Gui.this.setTitle("Indice:" + indice);
   }                                      

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new Gui().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton btnAnterior;
   private javax.swing.JButton btnCarregar;
   private javax.swing.JButton btnFim;
   private javax.swing.JButton btnGerar;
   private javax.swing.JButton btnInicio;
   private javax.swing.JButton btnNovo;
   private javax.swing.JButton btnProximo;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTextField txtArquivo;
   private javax.swing.JTextArea txtExplicacao;
   private javax.swing.JTextField txtPalavra;
   private javax.swing.JTextArea txtResposta;
   // End of variables declaration              
   
   Question question = new Question();
   ArrayList<Question> questions;
   int indice = 0;
}

